title: Image Manipulation
description: "August 2023 to June 2024"
owner_name: IJKT
github_username: trevorhuang1
github_repo: "frontend"
baseurl: "/image-manipulation"
#remote_theme: "lone-wolf-theme"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/trevorhuang1"}
    - { platform: github, user_url: "https://github.com/BearytheGreenBear"}
    - { platform: github, user_url: "https://github.com/iwu78"}
    - { platform: github, user_url: "https://github.com/jasonguan1012"}
remote_theme: jekyll/minima
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
